version: "3.8"
services:
  sql-db:
    build:
      context: ./sql/
      dockerfile: Dockerfile
    container_name: sql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: BrendenBookstoreDB
      MYSQL_USER: xbrenden
      MUSQL_PASSWORD: 1234
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring
  api:
    build:
      context: ./fullstack
      dockerfile: Dockerfile
    container_name: api
    networks:
      - spring
    depends_on:
      - sql-db
    ports:
      - 8080:8080

networks:
  spring:
