# Use the official Ubuntu image as the base
FROM ubuntu:latest

# Install necessary dependencies
RUN apt-get update && apt-get install -y software-properties-common default-jre wget

# Add the Microsoft SQL Server repository and GPG key
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"
# Set the SQL Server SA password (replace 'YourPassword' with your desired password)
ENV MSSQL_SA_PASSWORD='1234'

# Start SQL Server and configure it to accept remote connections
ADD localDump.sql /docker-entrypoint-initdb.d

# Download and install Apache Tomcat (replace 'TOMCAT_VERSION' with the desired version)
ARG TOMCAT_VERSION=9.0.60
RUN wget -q "https://downloads.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz" -O /tmp/tomcat.tar.gz && \
    tar xzvf /tmp/tomcat.tar.gz -C /opt && \
    ln -s /opt/apache-tomcat-${TOMCAT_VERSION} /opt/tomcat && \
    rm /tmp/tomcat.tar.gz

COPY BrendenBookstoreSession.war /usr/local/tomcat/webapps/

# Expose the default Tomcat port (8080)
EXPOSE 8080


# Start Apache Tomcat
CMD ["/opt/tomcat/bin/catalina.sh", "run"]

